# Generated by Django 2.0.7 on 2018-10-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilbyweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalparameter',
            name='name',
            field=models.CharField(choices=[('mass_1', 'Mass 1 (M☉)'), ('mass_2', 'Mass 2 (M☉)'), ('luminosity_distance', 'Luminosity Distance (Mpc)'), ('iota', 'iota'), ('psi', 'psi'), ('phase', 'Phase'), ('geocent_time', 'Merger Time (GPS Time)'), ('ra', 'Right Ascension (Radians)'), ('dec', 'Declination (Degrees)')], max_length=20),
        ),
    ]
