# Generated by Django 2.0.7 on 2018-10-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilbyweb', '0003_auto_20181010_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='submission_time',
        ),
    ]
