version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ng_bilby
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
  db:
    image: mysql:5.7
    container_name: mysql_bilby
    environment:
      MYSQL_ROOT_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_DATABASE: bilby
      MYSQL_USER: django
      MYSQL_PASSWORD: 76vcqmGKP19Z1AEx
    volumes:
      - var_lib_mysql:/var/lib/mysql
  web:
    build: ./
    container_name: dg_bilby
    command: >
      bash -c "pip install gunicorn
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn bilbyui.wsgi -b 0.0.0.0:8000"
    ports:
      - "8000"
    volumes:
      - ./:/code
      - ./static:/static
    depends_on:
      - db

volumes:
  var_lib_mysql:
