# Generated by Django 2.0.7 on 2018-07-25 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_choice', models.CharField(blank=True, choices=[('simulated', 'Simulated data'), ('open', 'Open data')], default='simulated', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Queued', 'Queued'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Error', 'Error'), ('Saved', 'Saved'), ('Wall Time Exceeded', 'Wall Time Exceeded'), ('Deleted', 'Deleted')], default='Draft', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('submission_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_choice', models.CharField(blank=True, choices=[('hanford', 'Hanford'), ('livingston', 'Livingston'), ('virgo', 'Virgo')], default='hanford', max_length=20)),
                ('signal_duration', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('sample_frequency', models.IntegerField(default=2048, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_time', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_open_data', to='tupakweb.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Sampler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('dynesty', 'Dynesty'), ('nestle', 'Nestle')], default='dynesty', max_length=15)),
                ('sampler_input_name', models.CharField(blank=True, choices=[('number_of_live_points', 'Number of live points'), ('number_of_steps', 'Number of steps'), ('not_applicable', 'N/A')], default='not_applicable', max_length=20)),
                ('sampler_input_value', models.IntegerField(null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_sampler', to='tupakweb.Job')),
            ],
        ),
        migrations.CreateModel(
            name='SignalBbh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('mass_1', 'Mass 1')], default='mass_1', max_length=20)),
                ('value', models.FloatField(null=True)),
                ('prior_fixed', models.FloatField(null=True)),
                ('prior_min', models.FloatField(null=True)),
                ('prior_max', models.FloatField(null=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal_injection_signal_bbh', to='tupakweb.Job')),
            ],
        ),
        migrations.CreateModel(
            name='SignalInjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inject_or_not', models.BooleanField(default=False)),
                ('SIGNAL_choice', models.CharField(blank=True, choices=[('bbh', 'Binary Black Hole')], default='bbh', max_length=50)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_signal_injection', to='tupakweb.Job')),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_choice', models.CharField(blank=True, choices=[('hanford', 'Hanford'), ('livingston', 'Livingston'), ('virgo', 'Virgo')], default='hanford', max_length=20)),
                ('signal_duration', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('sample_frequency', models.IntegerField(default=2048, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_time', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_simulated_data', to='tupakweb.Data')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_data', to='tupakweb.Job'),
        ),
        migrations.AlterUniqueTogether(
            name='simulateddata',
            unique_together={('data', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='signalinjection',
            unique_together={('job', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='signalbbh',
            unique_together={('signal', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='sampler',
            unique_together={('job', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='opendata',
            unique_together={('data', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('user', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('job', 'id')},
        ),
    ]
