# Generated by Django 2.0.7 on 2018-08-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='inject_or_not',
        ),
        migrations.AlterField(
            model_name='signal',
            name='signal_choice',
            field=models.CharField(blank=True, choices=[('binary_black_hole', 'Binary Black Hole')], default='binary_black_hole', max_length=50),
        ),
    ]
