# Generated by Django 2.0.7 on 2018-09-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplerdynesty',
            name='sampler',
        ),
        migrations.RemoveField(
            model_name='sampleremcee',
            name='sampler',
        ),
        migrations.RemoveField(
            model_name='samplernestle',
            name='sampler',
        ),
        migrations.AlterField(
            model_name='sampler',
            name='sampler_choice',
            field=models.CharField(choices=[('dynesty', 'Dynesty'), ('nestle', 'Nestle'), ('emcee', 'Emcee')], default='dynesty', max_length=15),
        ),
        migrations.DeleteModel(
            name='SamplerDynesty',
        ),
        migrations.DeleteModel(
            name='SamplerEmcee',
        ),
        migrations.DeleteModel(
            name='SamplerNestle',
        ),
    ]
