# Generated by Django 2.0.7 on 2018-08-01 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tupakweb', '0002_auto_20180730_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('user', 'name')},
        ),
    ]
