# Generated by Django 2.0.7 on 2018-08-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0002_auto_20180730_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_choice',
            field=models.CharField(choices=[('simulated', 'Simulated data'), ('open', 'Open data')], default='simulated', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dataopen',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='datasimulated',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='priorfixed',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prioruniform',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sampler',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='samplerdynesty',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sampleremcee',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='samplernestle',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='signal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='signalbbhparameter',
            unique_together=set(),
        ),
    ]
