# Generated by Django 2.0.7 on 2018-09-05 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0002_auto_20180905_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplerParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('sampler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupakweb.Sampler')),
            ],
        ),
    ]
