# Generated by Django 2.0.7 on 2018-08-07 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0003_auto_20180801_1745'),
        ('tupakweb', '0003_auto_20180803_1114'),
    ]

    operations = [
    ]
