# Generated by Django 2.0.7 on 2018-09-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0003_samplerparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_choice',
            field=models.CharField(choices=[('simulated', 'Simulated'), ('open', 'Open')], default='simulated', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error'), ('saved', 'Saved'), ('wall_time_exceeded', 'Wall Time Exceeded'), ('deleted', 'Deleted')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='signalparameter',
            name='name',
            field=models.CharField(choices=[('mass_1', 'Mass 1 (M☉)'), ('mass_2', 'Mass 2 (M☉)'), ('luminosity_distance', 'Luminosity Distance (Mpc)'), ('iota', 'iota'), ('psi', 'psi'), ('phase', 'Phase'), ('merger_time', 'Merger Time (GPS Time)'), ('ra', 'Right Ascension'), ('dec', 'Declination')], max_length=20),
        ),
    ]
