# Generated by Django 2.0.7 on 2018-08-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0003_auto_20180816_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='signal_choice',
            field=models.CharField(choices=[('binary_black_hole', 'Binary Black Hole')], default='binary_black_hole', max_length=50),
        ),
    ]
