# Generated by Django 2.0.7 on 2018-09-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0004_auto_20180905_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error'), ('saved', 'Saved'), ('wall_time_exceeded', 'Wall Time Exceeded'), ('deleted', 'Deleted'), ('public', 'Public')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='signalparameter',
            name='name',
            field=models.CharField(choices=[('mass_1', 'Mass 1 (M☉)'), ('mass_2', 'Mass 2 (M☉)'), ('luminosity_distance', 'Luminosity Distance (Mpc)'), ('iota', 'iota'), ('psi', 'psi'), ('phase', 'Phase'), ('merger_time', 'Merger Time (GPS Time)'), ('ra', 'Right Ascension (Radians)'), ('dec', 'Declination (Degrees)')], max_length=20),
        ),
    ]
