# Generated by Django 2.0.7 on 2018-08-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0004_merge_20180807_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataopen',
            name='detector_choice',
            field=models.CharField(choices=[('hanford', 'Hanford'), ('livingston', 'Livingston'), ('virgo', 'Virgo')], default='hanford', max_length=20),
        ),
        migrations.AlterField(
            model_name='datasimulated',
            name='detector_choice',
            field=models.CharField(choices=[('hanford', 'Hanford'), ('livingston', 'Livingston'), ('virgo', 'Virgo')], default='hanford', max_length=20),
        ),
    ]
