# Generated by Django 2.0.7 on 2018-08-16 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0004_auto_20180816_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
