# Generated by Django 2.0.7 on 2018-09-14 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0005_auto_20180906_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='signal_model',
            field=models.CharField(choices=[('binary_black_hole', 'Binary Black Hole')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
