# Generated by Django 2.0.7 on 2018-08-24 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0005_job_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalparameter',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_signal_parameter', to='tupakweb.Signal'),
        ),
    ]
