# Generated by Django 2.0.7 on 2018-08-25 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0006_auto_20180824_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataopen',
            name='sample_frequency',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dataopen',
            name='signal_duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dataopen',
            name='start_time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='datasimulated',
            name='sample_frequency',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='datasimulated',
            name='signal_duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='datasimulated',
            name='start_time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
