# Generated by Django 2.0.7 on 2018-08-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0007_auto_20180825_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupakweb.Data')),
            ],
        ),
        migrations.RemoveField(
            model_name='dataopen',
            name='job',
        ),
        migrations.RemoveField(
            model_name='datasimulated',
            name='job',
        ),
        migrations.DeleteModel(
            name='DataOpen',
        ),
        migrations.DeleteModel(
            name='DataSimulated',
        ),
    ]
