# Generated by Django 2.0.7 on 2018-08-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupakweb', '0008_auto_20180828_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='signal_choice',
            field=models.CharField(choices=[('skip', 'None'), ('binary_black_hole', 'Binary Black Hole')], default='skip', max_length=50),
        ),
        migrations.AlterField(
            model_name='signalparameter',
            name='name',
            field=models.CharField(choices=[('mass_1', 'Mass 1 (M☉)'), ('mass_2', 'Mass 2 (M☉)'), ('luminosity_distance', 'Luminosity distance (Mpc)'), ('iota', 'iota'), ('psi', 'psi'), ('phase', 'Phase'), ('merger_time', 'Merger time (GPS time)'), ('ra', 'Right ascension'), ('dec', 'Declination')], max_length=20),
        ),
    ]
